apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: secretstore
  namespace: default
spec:
  type: secretstores.azure.keyvault
  version: v1
  metadata:
  - name: vaultName
    value: daprexpkeyvault
  - name: spnClientId
    secretKeyRef:
      name: kvclientid
      key:  kvclientid    
auth:
  secretStore: kubernetes