kind: Deployment
apiVersion: apps/v1
metadata:
  name: packagecredproviderapp
  labels:
    app: packagecredproviderapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: packagecredproviderapp
  template:
    metadata:
      labels:
        app: packagecredproviderapp
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "packagecredproviderapp"
        dapr.io/app-port: "8000"
        dapr.io/log-level: "debug"
        dapr.io/config: "appconfig"
        dapr.io/log-as-json: "true"
        prometheus.io/scrape: "true"
        prometheus.io/port: "9090"
        prometheus.io/path: "/"
    spec:
      containers:
      - name: packagecredproviderapp
        image: daprexpacr.azurecr.io/packagecredprovider:latest
        ports:
        - containerPort: 8000