kind: Service
apiVersion: v1
metadata:
  name: deviceconfigupdateservice
  labels:
    app: deviceconfigupdateservice
spec:
  selector:
    app: deviceconfigupdateapp
  ports:
    - port: 5000
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: deviceconfigupdateapp
  labels:
    app: deviceconfigupdateapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deviceconfigupdateapp
  template:
    metadata:
      labels:
        app: deviceconfigupdateapp
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "deviceconfigupdateapp"
        dapr.io/app-port: "5000"
        dapr.io/log-level: "debug"
        dapr.io/config: "appconfig"
        dapr.io/log-as-json: "true"
        prometheus.io/scrape: "true"
        prometheus.io/port: "9090"
        prometheus.io/path: "/"
    spec:
      containers:
      - name: deviceconfigupdateapp
        image: deviceconfigupdate:latest
        imagePullPolicy: Never
        resources:
          requests:
            memory: "254Mi"
            cpu: "500m"
          limits:
            memory: "254Mi"
            cpu: "500m"
        ports:
        - containerPort: 5000
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: deviceconfigupdateservice-ingress
spec:
  rules:
  - http:
      paths:
      - path: /
        backend:
          serviceName: deviceconfigupdateservice
          servicePort: 5000