apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: credentialrequest-pubsub
  namespace: default
spec:
  type: pubsub.azure.servicebus
  version: v1
  metadata:
  - name: connectionString
    secretKeyRef:
      name: ServiceBusConnectionString
      key:  ServiceBusConnectionString    
auth:
  secretStore: secretstore