name: telemetry-api-build-and-push

env:
  PROJECT_FILE_PATH: './src/telemetry-receiver-api'

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths: 
      "${PROJECT_FILE_PATH}/**"
  pull_request:
    branches: [ main ]
    paths: 
      "${PROJECT_FILE_PATH}/**"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    
    - name: 'Resolve Project Dependencies Using Dotnet'
      shell: bash
      run: |
        docker login -u ${{secrets.docker_username}} -p ${{secrets.docker_pwd}}
        pushd '${{env.PROJECT_FILE_PATH}}'
        docker build --push -t daprexpacr.azurecr.io/telemetryreceiverapi:latest .
        popd
